version: '3'
services:
  app:
    container_name: graphql-exercise
    build: .
    volumes:
      - ../:/srv/
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
